### ISSUE TITLE
Idempotent requests not supported

### ISSUE THREAD

**Issue by nozpheratu** [rebelidealist/stripe-ruby-mock#234]
Seems [idempotent requests](https://stripe.com/docs/api?lang=curl#idempotent_requests) aren't supported using the following spec:

```ruby
def create_charge(token, uuid)
  Stripe::Charge.create(
    { amount: 1000, currency: 'usd', card: token, description: '...' }, 
    { idempotency_key: uuid }
  )
end

it 'makes an idempotent charge' do
  uuid = 'abc123'
  token = StripeMock.generate_card_token(last4: "9191", exp_year: 1984)
  expect{create_charge(token, uuid)}.to_not raise_error
  StripeMock.prepare_card_error(:incorrect_cvc)
  expect{create_charge(token, uuid)}.to_not raise_error
  expect{create_charge(token, uuid + '4')}.to raise_error
end

```

**Comment by kathyonu** [comment]
@nozpheratu , @alexmamonchik : Greetings, I have worked this Issue for untold hours now, and I must sy, it is a sweet bag of worms.  I explain ..
One : You are using old code, you need to change a few things to have working code. (see link below)
Two : You should provide the test result / error that shows when you run this code, it helps to see what is happening, so someone can answer the issue.
Three : Even with accurate and working codes, you have opened a can of worms, tests wise.  In attempting to resolve this issue i have seemed to have proven to myself, with tests, that the idempotency_key is never used, never available to be used, and so is appearing to be utterly pointless.  I have spent hours on the stripe freednode chatroom seeking answers, and so far, no one has proven my tests results to be incorrect .. the key is never used.  Not by stripe, nor by our application, so what worth, the idempotency_key.  I have written Stripe.com support and await an explanation, and .. I asked for working tests to prove the use and usage of the key in any scenario.  If Stripe cannot prove the usefulness, and show the tests that make use of the key, then .. the key is moot, of no use.  I will keep you informed on this one.

Also, you can see what tests I have so far developed to attempt to prove any actual usage of the idempotency_key .. and so far, it cannot even be used.  see : https://github.com/kathyonu/rails-stripe-rspec-tests/blob/master/spec/stripe/stripe_charge_idempotency_spec.rb

**Comment by nozpheratu** [comment]
@kathyonu How have you determined that the key isn't being used by stripe? Are you testing only in scope of stripe-ruby-mock?

**Comment by kathyonu** [comment]
Stripe support can at times take up to a week for a response.
The only tests I am working with are the tests I showed you.

**Comment by nozpheratu** [comment]
@kathyonu I'm suggesting that perhaps the bottle neck isn't Stripe, but instead this mocking library itself. I don't imagine tests involving idempotency_key would work out of the box just because Stripe supports it on their end. Somebody will likely have to explicitly support it on this end as well. None of your tests are actually hitting the Stripe servers so I don't think Stripe support will be able to offer much assistance.

With that said, I haven't delved too deep into the source code for this library, so perhaps it should just work.

**Comment by nozpheratu** [comment]
@kathyonu Actually I just tried to make a payment directly against the Stripe test environment servers using an idempotency key and it looks like it's working just fine. 

To verify it worked, I created an initial charge object using an CC containing an invalid CVC code and recorded the failing UUID I was using as an idempotency key. I then proceeded to create a completely new charge object with the failing UUID but this time with a VALID CC CVC code, the charge still failed failed with an "Incorrect CVC" error message just as expected.

Idempotency keys are by Stripe , somebody simply™ needs to support it on this end.

**Comment by kathyonu** [comment]
@nozpheratu Thank You !!! I will write a test tomorrow to simulate your described actions.  Also, I got a response from Andrew at Stripe Support that did not touch on this, so double well done.

**Comment by kathyonu** [comment]
@nozpheratu Greetings, i have not been able to keep to my own timetable !!! I also set the idempotency_key on the  back burner.  I do want to clarify somerthing .. the way Stripe tells it, the idempotency_key is not something that is generated anew for each person's charge request.  the way i read their info on it is, set the code with a alpha-numeric, and that's it.  So .. when you create a new object with an old key, this means that each idempotency_key should be auto-generated for each charge, but not on the second try, obviously.  when you say you created a completely new charge item the second time, i do presume you mean new name, new email address, new token so that nothing is the same except the idempotency_key.  Is that what you mean ?  If so, then Stripe documentation is a bit off on this matter of how to use the key.

Thank you for your response on this.

**Comment by nozpheratu** [comment]
@kathyonu No, the developer has to specify an idempotency_key. Yes, in practice an idempotency_key would be unique between two different charges. But I was using a duplicate key to simulate what should happen when a idempotency_key is used twice or n number of times: you should get the same response no matter what, regardless of whether the charge is perfectly valid or has errors. So yes, two different charges using the same key will get the same response.

I believe what the docs describe is accurate: 
> We'll always send back the same response for requests made with the same key

**Comment by kathyonu** [comment]
@nozpheratu i do not believe i implied the idempotency_key was supplied by stripe. i reread my sentence above and see that it can indeed be read as vague .. sorry .. no .. stripe does not supply idempotency_key, agreed.

Regarding this : "Yes, in practice an idempotency_key would be unique between two different charges." 
Stripe is not showing that and their documents do not imply nor suggest that, and yet ... that seems to be the case ?? i seek to write the tests, and .. nowhere can i find that simple but most important fact mentioned.  am i amiss on this ? did I miss something somewher ein the stripe documents ? hmmm
I will be going over it.

Regarding this : "The key thing that I was trying to point out here was that you can't replicate this using stripe-ruby-mock."  I have just this day awakened to the fact that .. because StripeMock is creating the tokens .. when the tests see that token in play .. the https call is indeed handled by the StripeMock GEM.  Until today .. i thought Stripe::Customer.create(data) would create the customer on Stripe.
I believe my confusion on this lasted so long because I run so many tests some with the mock, and  some without where i use visit page and fill_in and submit and such on the pages themselves, and those tests show up on stripe. 

Regarding the key itself and its quality of 'changed.'  One customer, one idempotency_key per charge.
Is that correct for you ? It seems correct for me.  So from that, follow me on this a bit .. when the new user on our site makes an error on their email format, and my app catches that error and sends them back to the page and shows them the error, and they correct it, and they resubmit the same order / charge with a now corrected email, if i resubmit the order with the same idempotency_key, the order will be refused as it has the new data but same key.  My answer to this is : the charge / order would not have made it to Stripe because, our app caught the email format error, and never fully submitted the order.  I will have to try that out.

Meanwhile .. i have no tests that can tests an idempotency_key and again i place this on the back burner so i can get some other works done.
