### ISSUE TITLE
undefined method `retrieve' for #<Stripe::StripeObject:0x007fa9590ae268>

### ISSUE THREAD

**Issue by TrevorHinesley** [rebelidealist/stripe-ruby-mock#294]
Doing either:

`cus.subscriptions.retrieve(subscription_id)`

or

`cus.sources.retrieve(cus.default_source)`

Causes this issue. It's like nested objects aren't mapping to the correct methods or something?

**Comment by yogeshjain999** [comment]
I am not able to reproduce this. What version of `stripe` and `stripe-ruby-mock
` are you using ? 
Apart from that, this issue isn't related to this repo, as given object is from `stripe` gem.

Sidenote -  `retrieve` is getting called on `Stripe::StripeObject`, but `cus.subscriptions` is of `Stripe::ListObject` type.

**Comment by TrevorHinesley** [comment]
Well, it works using the stripe gem, not using stripe-ruby-mock, that's what I'm saying. Mock is 2.2.1, Stripe is 1.31.0

**Comment by slash7** [comment]
Same issue.

**Comment by alexmamonchik** [comment]
@TrevorHinesley @slash7 still can't reproduce the error. Do you use gem from rubygems or github Mock repository in your projects?

**Comment by matteomelani** [comment]
+1 with stripe-mock 2.2.1 & stripe 1.31.0

**Comment by Aerlinger** [comment]
Having the same issue. The `retrieve` method works with the Stripe gem, but doesn't work with Stripe Mock. The stack trace also indicates the source of the error is with the Stripe gem:

`stripe (1.31.0) lib/stripe/stripe_object.rb:281:in `method_missing'`

However, is it possible the 1.3.1 Stripe gem is using a newer version of the Stripe REST API vs. what StripeMock is using? It seems as though the Stripe ruby client is configured remotely and queries the API for configuration. This API version is set from the settings in Stripe dashboard, so that would explain the inconsistent results above.

![image](https://cloud.githubusercontent.com/assets/604138/13382774/e01daa10-de4a-11e5-85bf-edfe8e93f38b.png)

Might Stripe mock be incompatible with the Stripe gem for newer versions of the Stripe API? @alexmamonchik @yogeshjain999 Are you both using an older version of the API?

Also, I found a related issue here: https://github.com/stripe/stripe-ruby/issues/88.

**Comment by Aerlinger** [comment]
Interestingly, reverting the Stripe gem back to `1.20.1` with `stripe-ruby-mock 2.1.1` resolves the issue in tests. 1.20.1 is about a year old though, so I'm very reluctant to use it in production.

**Comment by alexmamonchik** [comment]
@Aerlinger thanks for your opinion. That's very important for us. I use latest API version - "2016-02-23" and stripe (1.31.0) and StripeMock 2.2.1 from repo, not from rubygems. And I can't reproduce your error. I tried with older stripe and older API. May you help with that? That's open source gem, community contributes it, not only me. When  I have time I'll back to research your problem. But will be better if you do it. Don't use it in production, wait until someone fixed your problem.

**Comment by ryanlntn** [comment]
For what it's worth I'm seeing the same issue with `stripe 1.31.0` and `stripe-ruby-mock 2.2.1`. Pulling stripe-ruby-mock from master resolves the issue.

**Comment by alexmamonchik** [comment]
@ryanlntn @Aerlinger @matteomelani @slash7 @yogeshjain999 plsease, try stripe mock 2.2.2

**Comment by ziyan-junaideen** [comment]
Had a similar issue in an old project that had an old version of Stripe Gem. I updated stripe to 1.31.x and also this gem to 2.2.2 and now it appears to wrok. Thanks @alexmamonchik
