### ISSUE TITLE
Undoing subscription cancellation resets billing period

### ISSUE THREAD

**Issue by spect88** [rebelidealist/stripe-ruby-mock#314]
Stripe allows undoing subscription cancellation by setting the same plan id again and updating subscription. E.g.
```ruby
s = customer.subscriptions.retrieve(subscription_id)
s.plan = s.plan.id
s.save
```

StripeMock supports this only partially - `cancel_at_period_end` is cleared as expected, but the billing period (`current_period_start` an `current_period_end`) gets reset as well. Stripe doesn't do that.

**Comment by vadzimpiatkevich** [comment]
Stripe doesn't allow undoing subscription cancellation. E.g.
```
s = customer.subscriptions.retrieve(subscription_id)
s.delete
s.save # Stripe::InvalidRequestError: No such subscription
```
So _**we should forbid updating of cancelled subscription**_ according to stripe behavior.

But if you set the at_period_end parameter to true, stripe allows you to update the subscription because the subscription will remain active until the end of the period. You are correct about this case. Updating it will also change cancel_at_period_end back to false. And _**we shouldn't reset billing period**_.
Please let me know if something is wrong.

**Comment by spect88** [comment]
@vadzimpiatkevich Yes, that's exactly what I meant.

> And **stripe mock shouldn't reset billing period**.

This is what I reported as broken here.
