### ISSUE TITLE
SubscriptionItems are unimplemented

### ISSUE THREAD

**Issue by TrevorHinesley** [rebelidealist/stripe-ruby-mock#429]
https://stripe.com/docs/api#subscription_items

**Comment by amrdruid** [comment]
Any updates on this one ?

**Comment by nlively** [comment]
When I use `stripe-ruby-mock` to test creating a subscription with multiple SubscriptionItems, I get a `Stripe::InvalidRequestError: No such plan: `

This is happening because I am no longer specifying plan directly in the payload, but rather specifying one plan per SubscriptionItem in the `items` array, like this:

```
subscription = Stripe::Subscription.create(
         customer: 'cus_ABC',
         items: [
      { plan:'BASE_PRICE_PLAN1', quantity: 1 },
      { plan: 'PER_USER_PLAN1', quantity: num_users }
    ],
         coupon: 'XYZ',
       )
```

**Comment by distroid** [comment]
I have a same problem - `Stripe::InvalidRequestError: No such plan`

**Comment by distroid** [comment]
@amrdruid hi

as I see your PR already merged to master, but I still get an this error.

Also i have a new error with subscription item plan:
```ruby
undefined method `id' for #<Stripe::StripeObject:0x007ffdad088498>
```

StripeObject has only 3 fields:

```ruby
<Stripe::StripeObject:0x3fc7afc0af9c> JSON: {
  "amount": 999,
  "created": 1504035972,
  "currency": "usd"
}
```

**Comment by alexmamonchik** [comment]
I've added some endpoints for my requirements. Please, add anything else if you need more.
